---
  - name: populating facts
    azure_rm_virtualmachine_info:
      resource_group: "{{ items }}"
    with_items:
      - "{{resource_group}}" 
  - debug: 
      msg: "{{vms.name}}"

  - name: create Azure vm extension to enable HTTPS WinRM listener
    azure_rm_virtualmachine_extension:
      name: winrm-extension
      resource_group: "{{ items[0] }}"
      virtual_machine_name: "{{ items[1] }}"
      publisher: Microsoft.Compute
      virtual_machine_extension_type: CustomScriptExtension
      type_handler_version: 1.9
      settings: '{"commandToExecute": "powershell.exe -ExecutionPolicy ByPass -EncodedCommand {{winrm_enable_script}}"}'
      auto_upgrade_minor_version: true
    with_nested:
       - "{{resource_group}}"
       - "{{vms.name}}"

  - name: wait for the WinRM port to come online
    wait_for:
      port: 5986
      host: '{{azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress}}'
      timeout: 600

